--------------------------------------------------------
--  File creato - domenica-aprile-07-2024   
--------------------------------------------------------
DROP TABLE "CUSTOM_PROJECT_DWH"."GRM4_DIM_COMPANY_DWA";
--------------------------------------------------------
--  DDL for Table GRM4_DIM_COMPANY_DWA
--------------------------------------------------------

  CREATE TABLE "CUSTOM_PROJECT_DWH"."GRM4_DIM_COMPANY_DWA" 
   (	"COMPANY_COD" VARCHAR2(25 BYTE), 
	"COMPANY_DES" VARCHAR2(100 BYTE), 
	"CURRENCY_COD" VARCHAR2(10 BYTE), 
	"COUNTRY_COD" VARCHAR2(10 BYTE), 
	"SESSION_TAG" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

REM INSERTING into CUSTOM_PROJECT_DWH.GRM4_DIM_COMPANY_DWA
SET DEFINE OFF;

Insert into CUSTOM_PROJECT_DWH.GRM4_DIM_COMPANY_DWA (COMPANY_COD,COMPANY_DES,CURRENCY_COD,COUNTRY_COD,SESSION_TAG) values ('AT10','NovaGen Innovations Croazia','EUR','CR','3');
Insert into CUSTOM_PROJECT_DWH.GRM4_DIM_COMPANY_DWA (COMPANY_COD,COMPANY_DES,CURRENCY_COD,COUNTRY_COD,SESSION_TAG) values ('AU10','NovaGen Innovations Australia','AUD','AU','3');
Insert into CUSTOM_PROJECT_DWH.GRM4_DIM_COMPANY_DWA (COMPANY_COD,COMPANY_DES,CURRENCY_COD,COUNTRY_COD,SESSION_TAG) values ('BE10','NovaGen Innovations Belgium','EUR','BL','3');
Insert into CUSTOM_PROJECT_DWH.GRM4_DIM_COMPANY_DWA (COMPANY_COD,COMPANY_DES,CURRENCY_COD,COUNTRY_COD,SESSION_TAG) values ('BG10','NovaGen Innovations Bulgary','BGN','BG','3');
Insert into CUSTOM_PROJECT_DWH.GRM4_DIM_COMPANY_DWA (COMPANY_COD,COMPANY_DES,CURRENCY_COD,COUNTRY_COD,SESSION_TAG) values ('BR10','NovaGen Innovations Brasil','BRL','BR','3');
Insert into CUSTOM_PROJECT_DWH.GRM4_DIM_COMPANY_DWA (COMPANY_COD,COMPANY_DES,CURRENCY_COD,COUNTRY_COD,SESSION_TAG) values ('CN10','NovaGen Innovations China','CNY','CH','3');
Insert into CUSTOM_PROJECT_DWH.GRM4_DIM_COMPANY_DWA (COMPANY_COD,COMPANY_DES,CURRENCY_COD,COUNTRY_COD,SESSION_TAG) values ('DE10','NovaGen Innovations Germany','EUR','DE','3');
Insert into CUSTOM_PROJECT_DWH.GRM4_DIM_COMPANY_DWA (COMPANY_COD,COMPANY_DES,CURRENCY_COD,COUNTRY_COD,SESSION_TAG) values ('ES10','NovaGen Innovations Spain','EUR','SP','3');
Insert into CUSTOM_PROJECT_DWH.GRM4_DIM_COMPANY_DWA (COMPANY_COD,COMPANY_DES,CURRENCY_COD,COUNTRY_COD,SESSION_TAG) values ('FR10','NovaGen Innovations France','EUR','FR','3');
Insert into CUSTOM_PROJECT_DWH.GRM4_DIM_COMPANY_DWA (COMPANY_COD,COMPANY_DES,CURRENCY_COD,COUNTRY_COD,SESSION_TAG) values ('GR10','NovaGen Innovations Greece','EUR','GR','3');
Insert into CUSTOM_PROJECT_DWH.GRM4_DIM_COMPANY_DWA (COMPANY_COD,COMPANY_DES,CURRENCY_COD,COUNTRY_COD,SESSION_TAG) values ('HU10','NovaGen Innovations Hungary','HUF','HU','3');
Insert into CUSTOM_PROJECT_DWH.GRM4_DIM_COMPANY_DWA (COMPANY_COD,COMPANY_DES,CURRENCY_COD,COUNTRY_COD,SESSION_TAG) values ('IT10','NovaGen Innovations Italy','EUR','IT','3');
Insert into CUSTOM_PROJECT_DWH.GRM4_DIM_COMPANY_DWA (COMPANY_COD,COMPANY_DES,CURRENCY_COD,COUNTRY_COD,SESSION_TAG) values ('-1',null,null,null,null);
